### PR TITLE
slight change to about command

### PR DESCRIPTION
**Pull request by oliver194**
adds the missing "ms" to ping and makes it so the about title is always the bots name

### CODE REVIEW

**Review by warp32767 — COMMENTED** [review]
ok kaching

**Comment by warp32767** [comment]
fuck my bad i'll review better next time im checking olivers ball cancer of a codebase

**Comment by UsrBinLuna** [comment]
yes bitch rememebr to kaching responsibly dont drink and drive

**Comment by warp32767** [comment]
thanks

**Pull request merged**
